### ISSUE TITLE
Can't unset mirrorlist

### ISSUE THREAD

**Issue by szechyjs** [chef-cookbooks/yum-epel#14]
I have a deployment scenario in which I only want to use a specific `baseurl` for the repos. I can set this just fine with attributes, however there does not seem to be a way to unset `mirrorlist`.

**Comment by nkadel-skyhook** [comment]
Document it in the README.md,. please!

**Comment by someara** [comment]
It's already documented under "more examples". 
If you can find a way to make this more clear, documentation PRs are my favorite thing to merge!
-s
