### ISSUE TITLE
Error when installing with 'knife cookbook site install yum-epel'

### ISSUE THREAD

**Issue by AltJ** [chef-cookbooks/yum-epel#18]
I get this error when I try to install this cookbook:
ERROR: IOError: Cannot open or read <path to my workspace>/chef-repo/cookbooks/yum-epel/metadata.rb!

$ knife cookbook site install yum-epel
Installing yum-epel to <path to my workspace>/workspace/chef-repo/cookbooks
Checking out the master branch.
Creating pristine copy branch chef-vendor-yum-epel
Downloading yum-epel from the cookbooks site at version 0.6.0 to <path to my workspace>/chef-repo/cookbooks/yum-epel.tar.gz
Cookbook saved: <path to my workspace>/chef-repo/cookbooks/yum-epel.tar.gz
Removing pre-existing version.
Uncompressing yum-epel version 0.6.0.
removing downloaded tarball
1 files updated, committing changes
Creating tag cookbook-site-imported-yum-epel-0.6.0
Checking out the master branch.
Updating 662c3ad..ca575bc
Fast-forward
 cookbooks/yum-epel/CHANGELOG.md                         |  63 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 cookbooks/yum-epel/README.md                            | 162 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 cookbooks/yum-epel/attributes/default.rb                |   1 +
 cookbooks/yum-epel/attributes/epel-debuginfo.rb         |  28 ++++++++++++++++++++++++++++
 cookbooks/yum-epel/attributes/epel-source.rb            |  28 ++++++++++++++++++++++++++++
 cookbooks/yum-epel/attributes/epel-testing-debuginfo.rb |  28 ++++++++++++++++++++++++++++
 cookbooks/yum-epel/attributes/epel-testing-source.rb    |  28 ++++++++++++++++++++++++++++
 cookbooks/yum-epel/attributes/epel-testing.rb           |  28 ++++++++++++++++++++++++++++
 cookbooks/yum-epel/attributes/epel.rb                   |  28 ++++++++++++++++++++++++++++
 cookbooks/yum-epel/metadata.json                        |  34 ++++++++++++++++++++++++++++++++++
 cookbooks/yum-epel/recipes/default.rb                   |  61 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 11 files changed, 489 insertions(+)
 create mode 100644 cookbooks/yum-epel/CHANGELOG.md
 create mode 100644 cookbooks/yum-epel/README.md
 create mode 100644 cookbooks/yum-epel/attributes/default.rb
 create mode 100644 cookbooks/yum-epel/attributes/epel-debuginfo.rb
 create mode 100644 cookbooks/yum-epel/attributes/epel-source.rb
 create mode 100644 cookbooks/yum-epel/attributes/epel-testing-debuginfo.rb
 create mode 100644 cookbooks/yum-epel/attributes/epel-testing-source.rb
 create mode 100644 cookbooks/yum-epel/attributes/epel-testing.rb
 create mode 100644 cookbooks/yum-epel/attributes/epel.rb
 create mode 100644 cookbooks/yum-epel/metadata.json
 create mode 100644 cookbooks/yum-epel/recipes/default.rb
Cookbook yum-epel version 0.6.0 successfully installed
ERROR: IOError: Cannot open or read <path to my workspace>/chef-repo/cookbooks/yum-epel/metadata.rb!

**Comment by AltJ** [comment]
heh, upgrading my chef client 12.x fixed it ...

**Comment by someara** [comment]
Re-opening for reference... we should back port this fix to 11.x at least.

**Comment by AltJ** [comment]
You're a good man...

**Comment by err0** [comment]
is it just a matter of rebuilding the supermarket package?  I see metadata.rb here on github but it didn't make it down when I installed the 0.6 cookbook.

**Comment by someara** [comment]
This should be fixed up in the 11.x client now too.

https://github.com/chef/chef/commit/01ff4f9f0be41d293d17969a89686706ab7c3e99

-s
