### ISSUE TITLE
include_config in yum-epel recipe

### ISSUE THREAD

**Issue by pantocrator27** [chef-cookbooks/yum-epel#22]
I was noticing the include_config directive in the yum-epel repository and I cannot find any documentation on what this does?  Is this a remnant of some prior code?

**Comment by someara** [comment]
Hello!

It looks like it's just the DNF version of "includepkgs"

check out
http://dnf.readthedocs.org/en/latest/cli_vs_yum.html

and
https://bugzilla.redhat.com/show_bug.cgi?id=1055910

-s

**Comment by pantocrator27** [comment]
oh okay.  what i read in the documentation was that the directive is "include" but more importantly I guess I could not see where it tied into yum_repository and the yum cookbook.  

thanks!

**Comment by someara** [comment]
Feel free to send a PR to the yum README.md

=)
