### ISSUE TITLE
I'm having a problem with the ca-certificates

### ISSUE THREAD

**Issue by johnlabarge** [chef-cookbooks/yum-epel#23]
Specifically: 
 ---- Begin output of yum -q -y makecache --disablerepo=* --enablerepo=epel ----
==> default: STDOUT: 
==> default: STDERR: Error: Cannot retrieve metalink for repository: epel. Please verify its path and try again
==> default: ---- End output of yum -q -y makecache --disablerepo=* --enablerepo=epel ----
==> default: Ran yum -q -y makecache --disablerepo=* --enablerepo=epel returned 1

 is reported by the cookbook execution every time this is with version 0.6.2. 

Manually running : 
sudo yum upgrade ca-certificates --disablerepo=epel 
Resolves this issue.  I'm new to Chef, but going to try forking and fixing and will comment back.

**Comment by keir-rex** [comment]
Is there a more permanent workaround/fix for this? 
Currently, I have to:
 `$ vagrant up` fails to provision
Then SSH into the machine
run `$ sudo yum upgrade ca-certificates --disablerepo=epel` 
Finally run `$ vagrant provision`

**Comment by someara** [comment]
The "permanent" solution would be to create cookbook or recipe that does this for you, and put it in your run_list before yum-epel.

Im going out on a limb here and assuming you're on rhel/centos 5?

**Comment by keir-rex** [comment]
@someara I'm on centos 6.4... I did consider putting this into my recipe but it seems like a bit of a hack.
