### ISSUE TITLE
Low Priority - Consider adding Oracle Linux Support

### ISSUE THREAD

**Issue by LevonBecker** [chef-cookbooks/yum-epel#24]
I know it's a pain to test because there isn't a bento for oracle linux, but you may consider adding Oracle Linux support. It seems like it would be very straight forward and simple to add. Harder to test of course.

I made a base linux cookbook and had a client that used Oracle Linux (Not sure why), and went to add it and after a little rabbit holing I found this cookbook didn't have the platform dependency in the metadata.

Hah if I had an Oracle bento quick to grab I'd get off my lazy butt and fork for you guys etc.

**Comment by tas50** [comment]
Oracle is in the metadata and should be supported by the cookbook out the box.  If you have an example of a failure under Oracle let me know, but I don't see why this wouldn't work.
