### ISSUE TITLE
Deprecated messages on converge

### ISSUE THREAD

**Issue by jaseeey** [chef-cookbooks/yum-epel#25]
When using yum-epel, the following deprecated message is thrown when converging. Is this something that will be addressed going forward?

       Deprecated features used!
         baseurl nil currently does not overwrite the value of baseurl. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :baseurl, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:24:in `block (2 levels) in from_file'
         cost nil currently does not overwrite the value of cost. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :cost, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:25:in `block (2 levels) in from_file'
         enablegroups nil currently does not overwrite the value of enablegroups. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :enablegroups, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:28:in `block (2 levels) in from_file'
         exclude nil currently does not overwrite the value of exclude. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :exclude, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:29:in `block (2 levels) in from_file'
         fastestmirror_enabled nil currently does not overwrite the value of fastestmirror_enabled. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :fastestmirror_enabled, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:31:in `block (2 levels) in from_file'
         http_caching nil currently does not overwrite the value of http_caching. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :http_caching, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:34:in `block (2 levels) in from_file'
         include_config nil currently does not overwrite the value of include_config. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :include_config, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:35:in `block (2 levels) in from_file'
         includepkgs nil currently does not overwrite the value of includepkgs. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :includepkgs, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:36:in `block (2 levels) in from_file'
         keepalive nil currently does not overwrite the value of keepalive. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :keepalive, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:37:in `block (2 levels) in from_file'
         max_retries nil currently does not overwrite the value of max_retries. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :max_retries, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:38:in `block (2 levels) in from_file'
       hange your code to explicitly accept nil using "property :metadata_expire, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:39:in `block (2 levels) in from_file'
         mirror_expire nil currently does not overwrite the value of mirror_expire. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :mirror_expire, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:40:in `block (2 levels) in from_file'
         mirrorlist_expire nil currently does not overwrite the value of mirrorlist_expire. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :mirrorlist_expire, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:42:in `block (2 levels) in from_file'
         password nil currently does not overwrite the value of password. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :password, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:43:in `block (2 levels) in from_file'
       
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:44:in `block (2 levels) in from_file'
         proxy nil currently does not overwrite the value of proxy. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :proxy, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:45:in `block (2 levels) in from_file'
         proxy_username nil currently does not overwrite the value of proxy_username. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :proxy_username, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:46:in `block (2 levels) in from_file'
         proxy_password nil currently does not overwrite the value of proxy_password. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :proxy_password, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:47:in `block (2 levels) in from_file'
         report_instanceid nil currently does not overwrite the value of report_instanceid. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :report_instanceid, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:48:in `block (2 levels) in from_file'
         skip_if_unavailable nil currently does not overwrite the value of skip_if_unavailable. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :skip_if_unavailable, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:50:in `block (2 levels) in from_file'
         source nil currently does not overwrite the value of source. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :source, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:51:in `block (2 levels) in from_file'
         sslcacert nil currently does not overwrite the value of sslcacert. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :sslcacert, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:52:in `block (2 levels) in from_file'
         sslclientcert nil currently does not overwrite the value of sslclientcert. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :sslclientcert, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:53:in `block (2 levels) in from_file'
         sslclientkey nil currently does not overwrite the value of sslclientkey. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :sslclientkey, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:54:in `block (2 levels) in from_file'
         sslverify nil currently does not overwrite the value of sslverify. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :sslverify, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:55:in `block (2 levels) in from_file'
       be set to nil instead. Please change your code to explicitly accept nil using "property :timeout, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:56:in `block (2 levels) in from_file'
         username nil currently does not overwrite the value of username. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :username, [MyType, nil]", or stop setting this value to nil. at 1 location:
           - /tmp/kitchen/cookbooks/yum-epel/recipes/default.rb:57:in `block (2 levels) in from_file'

**Comment by someara** [comment]
Hello!

Fixing these up is definitely on our TODO (soon) lists... we're seeing these warnings on most of the cookbooks we maintain. The yum-* series is especially noisy because is uses a lot of nil attributes.

-s

**Comment by jaseeey** [comment]
Thank you for the response, looking forward to the fix!

**Comment by UlkaAsati** [comment]
any workaround to disable these warning messages?
