### ISSUE TITLE
latest release does no longer allow to turn off boolean settings

### ISSUE THREAD

**Issue by c-hoeger** [chef-cookbooks/yum-epel#28]
faulty commit is

https://github.com/chef-cookbooks/yum-epel/commit/941fd94db01bf11fdfcc9d6e900f54192ba8ac14

now it  is no longer possible to turn of e.g. gpgcheck and all this stuff

**Comment by miry** [comment]
Same problem:

gpgkey=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6

Here is log: https://gist.github.com/miry/71107cf7ef862652e231
