### ISSUE TITLE
the `mirrorlist` default value should be changed in the `epel.rb` attributes for linux 6 and 7

### ISSUE THREAD

**Issue by joshoohaah** [chef-cookbooks/yum-epel#31]
There appears to be this logic loop in the cookbook attribute file:
```
  case node['platform_version'].to_i
  when 5
    default['yum']['epel']['description'] = 'Extra Packages for Enterprise Linux 5 - $basearch'
    default['yum']['epel']['mirrorlist'] = 'http://mirrors.fedoraproject.org/mirrorlist?repo=epel-5&arch=$basearch'
    default['yum']['epel']['gpgkey'] = 'http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL'
  when 6
    default['yum']['epel']['description'] = 'Extra Packages for Enterprise Linux 6 - $basearch'
    default['yum']['epel']['mirrorlist'] = 'https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch'
    default['yum']['epel']['gpgkey'] = 'https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6'
  when 7
    default['yum']['epel']['description'] = 'Extra Packages for Enterprise Linux 7 - $basearch'
    default['yum']['epel']['mirrorlist'] = 'https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch'
    default['yum']['epel']['gpgkey'] = 'https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7'
  end
end
```

the default mirrorlist works fine on 5, which uses `http://mirrors.fedoraproject.org/mirrorlist?repo=`.  but 6 and 7 then start using `https://mirrors.fedoraproject.org/metalink?repo=`.  

The 'metalink' reference in the url does not seem to work by default and should be switched back to refence 'mirrorlist'.  Its true wrapper cookbooks can override this (which I do). but it would be convenient to have this fixed in the community cookbook as well.

**Comment by BrentOnRails** [comment]
the mirrorlist reference does not work for me

**Comment by iennae** [comment]
What does not work about the metalink for you @joshoohaah? Are you using on freshly installed systems, or is it failing for updates to existing systems? Might be something else that we need to fix here, just trying to understand what we are missing.

As per documentation:

mirrorlists (used by YUM)
Metalink format mirrorlist
Yum in Fedora 10 and higher can process the mirror list in metalink format, which provides additional security checking capability. Yum compares the SHA1 checksums of each repository's repomd.xml file against that of the master mirrors. This ensures that significantly out-of-date mirrors are not used.

The yum repo file URL format is:

metalink=http://mirrors.fedoraproject.org/metalink?repo=fedora-10&arch=$basearch
Traditional mirrorlist
Yum also can process a mirror list in plain text format.

The yum repo file URL format is:

mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=fedora-10&arch=$basearch

**Comment by iennae** [comment]
I've changed these all to mirrorlist to simplify the attributes setting and it works fine on the testing I did. Please reopen if this is an issue.
