### ISSUE TITLE
Version constrait on yum in 0.6.6 may be overly restrictive

### ISSUE THREAD

**Issue by agperson** [chef-cookbooks/yum-epel#33]
### Cookbook version
0.6.6

### Chef-client version
12.8.1

### Platform Details
Berkshelf

### Scenario:
Version contrait on yum was updated:
```
-depends 'yum', '~> 3.2'
+depends 'yum', '~> 3.10.0'
```
However this may be overly restrictive.  The `make_cache` option appeared in 3.3, so its unclear to me why 3.10 is a minimum.  Furthermore, the new version lock will restrict to 3.10.x in the future. This conflicts with other cookbooks that also have strong version constraints.

### Steps to Reproduce:
In my case the conflict is with a specific version of openstack-common:
```
Unable to satisfy the following requirements:

- `yum (~> 3.5.4)` required by `openstack-common-11.5.1`
- `yum (~> 3.10.0)` required by `yum-epel-0.6.6`
```

### Actual Result:

**Comment by tas50** [comment]
I changed this to >= 3.6.3. There were some important header cleaning changes there that we should be requiring.
