### ISSUE TITLE
mirrorlist is missing in /etc/yum.repo.d/epel-testing.repo

### ISSUE THREAD

**Issue by TakiTake** [chef-cookbooks/yum-epel#36]
### Cookbook version
0.7.1

### Chef-client version
Chef: 12.4.1

### Platform Details
CentOS 6.3 x86_64

### Scenario:
From v0.7.1 attribute name in epel-testing.rb is changed then yum command raise error.
Because gpgkey and mirrorlist are missing in /etc/yum.repo.d/epel-testing.repo.

```
# This file was generated by Chef
# Do NOT modify this file by hand.

[epel-testing]
name=Extra Packages for $releasever - $basearch - Testing 
enabled=1
failovermethod=priority
gpgcheck=1
```

### Steps to Reproduce:
After converge yum-epel cookbook try to yum update.

```
$ yum update
```

### Expected Result:
Setting up Update Process

### Actual Result:
```
Error: Cannot find a valid baseurl for repo: epel-testing
```

**Comment by iennae** [comment]
This should be fixed with version 1.0.1 of the cookbook.
