### ISSUE TITLE
NoMethodError: No resource or method named `yum_repository' for `ChefCompat::Recipe "default"'

### ISSUE THREAD

**Issue by knightsamar** [chef-cookbooks/yum-epel#41]
### Cookbook version
latest (2.0.0)

### Chef-client version
12.10.24

### Platform Details
CentOS 7.3 inside the kitchen vm.
Debian 8.6 on workstation

### Scenario:
Using the cookbook.

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
* Create a new cookbook
* Add `depends yum-epel` to a dependent cookbook's `metadata.rb`
* Put `include_recipe 'yum-epel' if platform_family?('rhel')` in the default recipe.
* Run `kitchen converge <centos-instance-suite>`

### Expected Result:
The resource should converge on a centos instance.

### Actual Result:
```
  NoMethodError
  -------------
  No resource or method named `yum_repository' for `ChefCompat::Recipe "default"'
```
Detailed traceback at https://gist.github.com/knightsamar/3137173169a058c1a331afb6c50e65b4

**Comment by tas50** [comment]
This should be fixed with the newer compat_resource dependency
