### ISSUE TITLE
disable other repositories / get packages from epel

### ISSUE THREAD

**Issue by rgerbranda** [chef-cookbooks/yum-epel#46]
### Cookbook version
2.1.1

### Chef-client version
latest

### Platform Details
Amazon Linux AMI release 2016.09 x86_64

### Scenario:
I want to install some packages from the epel repository: nrpe, nagios-plugins-uptime
The problem is that the packages are also in the Amazon repository, but very outdated

How to disable amzn-main repository?

### Steps to Reproduce:
yum_repository 'epel' do
  description 'Extra Packages for Enterprise Linux'
  mirrorlist 'http://mirrors.fedoraproject.org/mirrorlist?repo=epel-6&arch=$basearch'
  gpgkey 'http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6'
  action :create
  only_if { platform_family?('rhel') }
end

  package ['nrpe', 'nagios-plugins', 'nagios-plugins-disk', 'nagios-plugins-load', 'nagios-plugins-uptime']

### Expected Result:
nagios-plugins.x86_64                                                                         2.1.4-3.el6                                                                 epel
nagios-plugins-disk.x86_64                                                                    2.1.4-3.el6                                                                 epel
nagios-plugins-load.x86_64                                                                    2.1.4-3.el6                                                                 epel
nrpe.x86_64                                                                                   2.15-7.el6                                                                  epel

### Actual Result:
nagios-common.x86_64                                                                       3.5.1-1.8.amzn1                                                          @amzn-main
nagios-plugins.x86_64                                                                      1.4.16-5.8.amzn1                                                         @amzn-main
nagios-plugins-disk.x86_64                                                                 1.4.16-5.8.amzn1                                                         @amzn-main
nagios-plugins-load.x86_64                                                                 1.4.16-5.8.amzn1                                                         @amzn-main

**Comment by cheeseplus** [comment]
You'll want to look into setting the priority level on the `yum_respository` resource such that it's higher than the Amazon one. Closing this as it's not an issue with the cookbook but please do come ask us in http://community-slack.chef.io/ if you have questions.
