### ISSUE TITLE
Cannot install yum-epel 

### ISSUE THREAD

**Issue by ScarlettGatelyClark** [chef-cookbooks/yum-epel#49]
### Cookbook version
2.1.2

### Chef-client version
[Version of chef-client in your environment]

### Platform Details
debian and ubuntu 

### Scenario:
ruby_build depends on this and this depends on compat_resource. Notably compat_resource has been depreciated and moved to boneyard, I don't know if that has anything to do with failure.

### Steps to Reproduce:
knife supermarket install ruby_build ( which pulls this in as dep and this deps on compat_resource )

### Expected Result:
This to install.

### Actual Result:
DEBUG: Streaming download from https://supermarket.chef.io/api/v1/cookbooks/yum-epel/versions/2.1.2/download to tempfile /tmp/chef-rest20180131-4874-hb6ew2
DEBUG: content_encoding = ''               initializing noop stream deflator.
DEBUG: Chef::HTTP::StreamHandler calling Chef::HTTP::ValidateContentLength::ContentLengthCounter#handle_chunk
DEBUG: Chef::HTTP::StreamHandler calling Chef::HTTP::Decompressor::NoopInflater#handle_chunk
DEBUG: Chef::HTTP::StreamHandler calling Chef::HTTP::ValidateContentLength::ContentLengthCounter#handle_chunk
DEBUG: Chef::HTTP::StreamHandler calling Chef::HTTP::Decompressor::NoopInflater#handle_chunk
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_stream_complete
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_stream_complete
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_stream_complete
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_stream_complete
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_stream_complete
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_stream_complete
Cookbook saved: /tmp/kitchen/cookbooks/yum-epel.tar.gz
Removing pre-existing version.
Uncompressing yum-epel version 2.1.2.
Removing downloaded tarball
No changes made to yum-epel
Checking out the master branch.
Installing compat_resource to /tmp/kitchen/cookbooks
Checking out the master branch.
Creating pristine copy branch chef-vendor-compat_resource
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://supermarket.chef.io/api/v1/cookbooks/compat_resource
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-REMOTE-REQUEST-ID: 130dfb7e-90f4-4e70-816e-ceed7098546d
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: cache-control: max-age=0, private, must-revalidate
DEBUG: content-encoding: gzip
DEBUG: content-type: application/json; charset=utf-8
DEBUG: date: Wed, 31 Jan 2018 11:07:51 GMT
DEBUG: etag: W/"f880a34810485ffd5b8f40e65497db0c"
DEBUG: server: nginx/1.10.2
DEBUG: x-content-type-options: nosniff
DEBUG: x-frame-options: SAMEORIGIN
DEBUG: x-request-id: 259f5d7e-0ed1-4a9e-af44-d2d3e702f842
DEBUG: x-runtime: 0.040777
DEBUG: x-xss-protection: 1; mode=block
DEBUG: content-length: 1007
DEBUG: connection: Close
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/knife/cookbook_site_download.rb:108:in `basename': no implicit conversion of nil into String (TypeError)
	from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/knife/cookbook_site_download.rb:108:in `replacement_cookbook'
	from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/knife/cookbook_site_download.rb:50:in `run'
	from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/knife/cookbook_site_install.rb:147:in `download_cookbook_to'
	from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/knife/cookbook_site_install.rb:98:in `run'
	from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/knife/cookbook_site_install.rb:124:in `block in run'
	from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/knife/cookbook_site_install.rb:119:in `each'
	from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/knife/cookbook_site_install.rb:119:in `run'
	from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/knife/cookbook_site_install.rb:124:in `block in run'
	from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/knife/cookbook_site_install.rb:119:in `each'
	from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/knife/cookbook_site_install.rb:119:in `run'
	from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'
	from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'
	from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/knife.rb:220:in `run'
	from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/lib/chef/application/knife.rb:160:in `run'
	from /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.7.16/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:59:in `load'
	from /usr/bin/knife:59:in `<main>'

**Comment by tas50** [comment]
We're not longer using compat_resource so any compat_resource issues should be no more. Can you give the 3.X release branch a try and open this back up if you're still running into issues.
