### ISSUE TITLE
ERROR: TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by kamal2222ahmed** [chef-cookbooks/yum-epel#50]
### Cookbook version
2.1.2

### Chef-client version
Chef: 13.6.4

### Platform Details
Red Hat Enterprise Linux Server release 7.4 (Maipo), AWS

### Scenario:
site install 

### Steps to Reproduce:
knife cookbook site install yum-epel
### Expected Result:
gets installed / copied in the chef-repo

### Actual Result:
]$ knife cookbook site install yum-epel
Installing yum-epel to /home/ec2-user/alpha-chefrepo/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-yum-epel) exists, switching to it.
Downloading yum-epel from Supermarket at version 2.1.2 to /home/ec2-user/alpha-chefrepo/cookbooks/yum-epel.tar.gz
Cookbook saved: /home/ec2-user/alpha-chefrepo/cookbooks/yum-epel.tar.gz
Removing pre-existing version.
Uncompressing yum-epel version 2.1.2.
Removing downloaded tarball
No changes made to yum-epel
Checking out the master branch.
Installing compat_resource to /home/ec2-user/alpha-chefrepo/cookbooks
Checking out the master branch.
Creating pristine copy branch chef-vendor-compat_resource
ERROR: TypeError: no implicit conversion of nil into String

**Comment by dylankolson** [comment]
+1

**Comment by yanivmn** [comment]
+1

**Comment by tas50** [comment]
This isn't a bug in this cookbook, but an issue with knife in the chef/chef repo. You'll want to file it there if it's still happening with the latest copy of chef. 13.6 is quite old at this point and is no longer supported.
